### PR TITLE
Fix missing radar overlay on OpenGL ES

### PR DESCRIPTION
**Pull request by ryrobes**
Omastorm is really cool—thanks for building it! This fixes a blank radar overlay on my NVIDIA/Wayland setup while preserving the existing appearance in all three treatments.

The engine was receiving complete KMLB scans, but the radar shader failed to compile on an RTX 3090 Ti with NVIDIA 610.57.04. Wayland selected the packaged GLSL ES 100 variant, which contains a constant-array initializer that is not valid for that target:

```text
error C7516: OpenGL does not allow constant arrays
error C7553: OpenGL array assignments require #version 120
Failed to build graphics pipeline state
```

The same UI and data rendered successfully through desktop OpenGL offscreen. Since all treatments share the fragment shader, the compilation failure also hides the overlay in Pixels and Stipple modes.

This replaces the nine-element glyph density array with a scalar lookup returning exactly the same values and rebuilds the committed shader package. It adds no driver-specific branch and changes neither sampling nor the density pattern. The rendering harness also drops its stale assertion/replacement for the already-removed `sweep.frag.qsb`, which otherwise prevents both GPU tests from starting.

Validation:

- `bash scripts/check.sh`: all checks passed.
- `bash scripts/cargo.sh test --offline --locked -- --ignored rendering`: both GPU tests passed; zero mismatches across 22 radar scenes and the pan comparison.
- `bash scripts/capture-review.sh`: passed with an isolated daemon/cache, including theme changes.
- `glslangValidator`: the original packaged ES 100 shader fails; the corrected ES 100, GLSL 120, and GLSL 150 variants pass.
- Pixels, Glyphs, and Stipple verified under Wayland/OpenGL ES on the NVIDIA GPU. The installed Omarchy plugin was then updated and its working radar overlay confirmed on screen.

The running shell retained the old shader after a plugin rescan on my machine; restarting it with `omarchy restart shell` picked up the rebuilt package. Other GPU/driver combinations have not been tested here.

### CODE REVIEW

**Comment by Yani3rt** [comment]
Independent confirmation on a second NVIDIA model:

- Omastorm `0.1.2`, checkout `9920150ec413c692165bb7aa528d6b3eba9c318f`
- NVIDIA GeForce RTX 2060 (`TU106`), `nvidia-open-dkms` / `nvidia-utils` `610.57.04-1`
- Qt Declarative and Shader Tools `6.11.2-1`; `qsb 6.11.2`
- Omarchy `4.0.2-1`, Wayland

The engine was healthy and continuously produced fresh KBYX sweep textures,
while the basemap rendered without the radar layer. The user journal repeated:

```text
Failed to compile shader: 0(5) : error C7516: OpenGL does not allow constant arrays
0(5) : error C7553: OpenGL array assignments require #version 120
Failed to build graphics pipeline state
```

I independently applied the same scalar `densityAt` lookup used in this PR and
rebuilt the QSB. The resulting `radar.frag.qsb` has SHA-256
`414aecac7a024eb23bc536930790a2a60b847b663d895500e96b4bb40ba8ae74`.

Verification on the affected runtime path:

- `qsb --dump` contains no legacy GLSL constant array.
- After restarting `omarchy-shell`, a fresh journal window contains no shader
  compilation or graphics-pipeline failures.
- A window-only capture confirms that radar cells render over the KBYX map.
- The independent `check-map-tiles` check passes.

This PR fixes the reported failure on the RTX 2060 as well.

**Comment by wesleygrimes** [comment]
@ryrobes this one’s good to go after a rebase onto main — same blank-radar fix, and I’d like to take this over #22. I can’t update the branch from here (maintainer edits aren’t enabled on the fork). Could you rebase, or tick “Allow edits from maintainers” so I can?

**Comment by wesleygrimes** [comment]
Landed this as #62 on current main. Same densityAt lookup, rebuilt qsb. Thanks for catching it on NVIDIA. Closing this one because the rebase onto main was dirty.
